title: Home
name: Gilbert Rotich
author: Gilbert Rotich
description: Academic CV and Portfolio
email: grotich@usf.edu

# Add navigation menu
header_pages:
  - index.md
  - news.md
  - papers.md
  - experience.md
  - projects/index.md
